/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AuthSignInRouteImport } from './routes/auth.sign-in'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth.forgot-password'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppLifeEventsRouteImport } from './routes/app.life-events'
import { Route as AppGoalsRouteImport } from './routes/app.goals'
import { Route as AppFinancialsRouteImport } from './routes/app.financials'
import { Route as AppFamilyRouteImport } from './routes/app.family'
import { Route as AppCopilotRouteImport } from './routes/app.copilot'
import { Route as AppFamilyIndexRouteImport } from './routes/app.family.index'
import { Route as AppFamilySchemesRouteImport } from './routes/app.family.schemes'
import { Route as AppFamilyRecommendationsRouteImport } from './routes/app.family.recommendations'
import { Route as AppFamilyInsuranceRouteImport } from './routes/app.family.insurance'
import { Route as AppFamilyGoalsRouteImport } from './routes/app.family.goals'
import { Route as AppFamilyAddRouteImport } from './routes/app.family.add'
import { Route as AppFamilyMembersIdRouteImport } from './routes/app.family.members.$id'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppLifeEventsRoute = AppLifeEventsRouteImport.update({
  id: '/life-events',
  path: '/life-events',
  getParentRoute: () => AppRoute,
} as any)
const AppGoalsRoute = AppGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => AppRoute,
} as any)
const AppFinancialsRoute = AppFinancialsRouteImport.update({
  id: '/financials',
  path: '/financials',
  getParentRoute: () => AppRoute,
} as any)
const AppFamilyRoute = AppFamilyRouteImport.update({
  id: '/family',
  path: '/family',
  getParentRoute: () => AppRoute,
} as any)
const AppCopilotRoute = AppCopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => AppRoute,
} as any)
const AppFamilyIndexRoute = AppFamilyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppFamilyRoute,
} as any)
const AppFamilySchemesRoute = AppFamilySchemesRouteImport.update({
  id: '/schemes',
  path: '/schemes',
  getParentRoute: () => AppFamilyRoute,
} as any)
const AppFamilyRecommendationsRoute =
  AppFamilyRecommendationsRouteImport.update({
    id: '/recommendations',
    path: '/recommendations',
    getParentRoute: () => AppFamilyRoute,
  } as any)
const AppFamilyInsuranceRoute = AppFamilyInsuranceRouteImport.update({
  id: '/insurance',
  path: '/insurance',
  getParentRoute: () => AppFamilyRoute,
} as any)
const AppFamilyGoalsRoute = AppFamilyGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => AppFamilyRoute,
} as any)
const AppFamilyAddRoute = AppFamilyAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => AppFamilyRoute,
} as any)
const AppFamilyMembersIdRoute = AppFamilyMembersIdRouteImport.update({
  id: '/members/$id',
  path: '/members/$id',
  getParentRoute: () => AppFamilyRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/app/copilot': typeof AppCopilotRoute
  '/app/family': typeof AppFamilyRouteWithChildren
  '/app/financials': typeof AppFinancialsRoute
  '/app/goals': typeof AppGoalsRoute
  '/app/life-events': typeof AppLifeEventsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/app/': typeof AppIndexRoute
  '/app/family/add': typeof AppFamilyAddRoute
  '/app/family/goals': typeof AppFamilyGoalsRoute
  '/app/family/insurance': typeof AppFamilyInsuranceRoute
  '/app/family/recommendations': typeof AppFamilyRecommendationsRoute
  '/app/family/schemes': typeof AppFamilySchemesRoute
  '/app/family/': typeof AppFamilyIndexRoute
  '/app/family/members/$id': typeof AppFamilyMembersIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/app/copilot': typeof AppCopilotRoute
  '/app/financials': typeof AppFinancialsRoute
  '/app/goals': typeof AppGoalsRoute
  '/app/life-events': typeof AppLifeEventsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/app': typeof AppIndexRoute
  '/app/family/add': typeof AppFamilyAddRoute
  '/app/family/goals': typeof AppFamilyGoalsRoute
  '/app/family/insurance': typeof AppFamilyInsuranceRoute
  '/app/family/recommendations': typeof AppFamilyRecommendationsRoute
  '/app/family/schemes': typeof AppFamilySchemesRoute
  '/app/family': typeof AppFamilyIndexRoute
  '/app/family/members/$id': typeof AppFamilyMembersIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/app/copilot': typeof AppCopilotRoute
  '/app/family': typeof AppFamilyRouteWithChildren
  '/app/financials': typeof AppFinancialsRoute
  '/app/goals': typeof AppGoalsRoute
  '/app/life-events': typeof AppLifeEventsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/app/': typeof AppIndexRoute
  '/app/family/add': typeof AppFamilyAddRoute
  '/app/family/goals': typeof AppFamilyGoalsRoute
  '/app/family/insurance': typeof AppFamilyInsuranceRoute
  '/app/family/recommendations': typeof AppFamilyRecommendationsRoute
  '/app/family/schemes': typeof AppFamilySchemesRoute
  '/app/family/': typeof AppFamilyIndexRoute
  '/app/family/members/$id': typeof AppFamilyMembersIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/onboarding'
    | '/app/copilot'
    | '/app/family'
    | '/app/financials'
    | '/app/goals'
    | '/app/life-events'
    | '/app/profile'
    | '/app/reports'
    | '/app/settings'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/app/'
    | '/app/family/add'
    | '/app/family/goals'
    | '/app/family/insurance'
    | '/app/family/recommendations'
    | '/app/family/schemes'
    | '/app/family/'
    | '/app/family/members/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/app/copilot'
    | '/app/financials'
    | '/app/goals'
    | '/app/life-events'
    | '/app/profile'
    | '/app/reports'
    | '/app/settings'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/app'
    | '/app/family/add'
    | '/app/family/goals'
    | '/app/family/insurance'
    | '/app/family/recommendations'
    | '/app/family/schemes'
    | '/app/family'
    | '/app/family/members/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/onboarding'
    | '/app/copilot'
    | '/app/family'
    | '/app/financials'
    | '/app/goals'
    | '/app/life-events'
    | '/app/profile'
    | '/app/reports'
    | '/app/settings'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/app/'
    | '/app/family/add'
    | '/app/family/goals'
    | '/app/family/insurance'
    | '/app/family/recommendations'
    | '/app/family/schemes'
    | '/app/family/'
    | '/app/family/members/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignInRoute: typeof AuthSignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/life-events': {
      id: '/app/life-events'
      path: '/life-events'
      fullPath: '/app/life-events'
      preLoaderRoute: typeof AppLifeEventsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/goals': {
      id: '/app/goals'
      path: '/goals'
      fullPath: '/app/goals'
      preLoaderRoute: typeof AppGoalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/financials': {
      id: '/app/financials'
      path: '/financials'
      fullPath: '/app/financials'
      preLoaderRoute: typeof AppFinancialsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/family': {
      id: '/app/family'
      path: '/family'
      fullPath: '/app/family'
      preLoaderRoute: typeof AppFamilyRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/copilot': {
      id: '/app/copilot'
      path: '/copilot'
      fullPath: '/app/copilot'
      preLoaderRoute: typeof AppCopilotRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/family/': {
      id: '/app/family/'
      path: '/'
      fullPath: '/app/family/'
      preLoaderRoute: typeof AppFamilyIndexRouteImport
      parentRoute: typeof AppFamilyRoute
    }
    '/app/family/schemes': {
      id: '/app/family/schemes'
      path: '/schemes'
      fullPath: '/app/family/schemes'
      preLoaderRoute: typeof AppFamilySchemesRouteImport
      parentRoute: typeof AppFamilyRoute
    }
    '/app/family/recommendations': {
      id: '/app/family/recommendations'
      path: '/recommendations'
      fullPath: '/app/family/recommendations'
      preLoaderRoute: typeof AppFamilyRecommendationsRouteImport
      parentRoute: typeof AppFamilyRoute
    }
    '/app/family/insurance': {
      id: '/app/family/insurance'
      path: '/insurance'
      fullPath: '/app/family/insurance'
      preLoaderRoute: typeof AppFamilyInsuranceRouteImport
      parentRoute: typeof AppFamilyRoute
    }
    '/app/family/goals': {
      id: '/app/family/goals'
      path: '/goals'
      fullPath: '/app/family/goals'
      preLoaderRoute: typeof AppFamilyGoalsRouteImport
      parentRoute: typeof AppFamilyRoute
    }
    '/app/family/add': {
      id: '/app/family/add'
      path: '/add'
      fullPath: '/app/family/add'
      preLoaderRoute: typeof AppFamilyAddRouteImport
      parentRoute: typeof AppFamilyRoute
    }
    '/app/family/members/$id': {
      id: '/app/family/members/$id'
      path: '/members/$id'
      fullPath: '/app/family/members/$id'
      preLoaderRoute: typeof AppFamilyMembersIdRouteImport
      parentRoute: typeof AppFamilyRoute
    }
  }
}

interface AppFamilyRouteChildren {
  AppFamilyAddRoute: typeof AppFamilyAddRoute
  AppFamilyGoalsRoute: typeof AppFamilyGoalsRoute
  AppFamilyInsuranceRoute: typeof AppFamilyInsuranceRoute
  AppFamilyRecommendationsRoute: typeof AppFamilyRecommendationsRoute
  AppFamilySchemesRoute: typeof AppFamilySchemesRoute
  AppFamilyIndexRoute: typeof AppFamilyIndexRoute
  AppFamilyMembersIdRoute: typeof AppFamilyMembersIdRoute
}

const AppFamilyRouteChildren: AppFamilyRouteChildren = {
  AppFamilyAddRoute: AppFamilyAddRoute,
  AppFamilyGoalsRoute: AppFamilyGoalsRoute,
  AppFamilyInsuranceRoute: AppFamilyInsuranceRoute,
  AppFamilyRecommendationsRoute: AppFamilyRecommendationsRoute,
  AppFamilySchemesRoute: AppFamilySchemesRoute,
  AppFamilyIndexRoute: AppFamilyIndexRoute,
  AppFamilyMembersIdRoute: AppFamilyMembersIdRoute,
}

const AppFamilyRouteWithChildren = AppFamilyRoute._addFileChildren(
  AppFamilyRouteChildren,
)

interface AppRouteChildren {
  AppCopilotRoute: typeof AppCopilotRoute
  AppFamilyRoute: typeof AppFamilyRouteWithChildren
  AppFinancialsRoute: typeof AppFinancialsRoute
  AppGoalsRoute: typeof AppGoalsRoute
  AppLifeEventsRoute: typeof AppLifeEventsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCopilotRoute: AppCopilotRoute,
  AppFamilyRoute: AppFamilyRouteWithChildren,
  AppFinancialsRoute: AppFinancialsRoute,
  AppGoalsRoute: AppGoalsRoute,
  AppLifeEventsRoute: AppLifeEventsRoute,
  AppProfileRoute: AppProfileRoute,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignInRoute: AuthSignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
